"""
JULIUS Behavioral Detection Engine — Runs pattern rules against live events.
"""

import logging
import json
import time
from datetime import datetime, timedelta
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)

_last_check_time: Optional[str] = None
_running = False


def run_detection_cycle(db):
    """Check recent events against all active behavioral patterns."""
    global _last_check_time, _running
    _running = True

    try:
        cutoff = _last_check_time or (datetime.utcnow() - timedelta(seconds=60)).isoformat()
        _last_check_time = datetime.utcnow().isoformat()

        patterns = db.get_behavioral_patterns()
        active_patterns = [p for p in patterns if p.get("is_active")]
        if not active_patterns:
            return

        recent_events = db.get_recent_events(200)
        new_events = [e for e in recent_events if e.get("timestamp", "") > cutoff]
        if not new_events:
            return

        for pattern in active_patterns:
            matches = evaluate_pattern(pattern, new_events)
            if matches:
                alert = generate_alert(pattern, matches)
                db.add_behavioral_alert(
                    pattern_id=pattern["id"],
                    alert_type=alert["alert_type"],
                    severity=alert["severity"],
                    message=alert["message"],
                    data=alert["data"],
                )
                db.add_event(
                    event_id=f"evt_behav_alert_{int(time.time() * 1000)}",
                    event_type="behavioral_alert_generated",
                    source="julius-behavioral-engine",
                    data={"pattern_id": pattern["id"], "pattern_name": pattern["name"],
                           "matched_events": len(matches)},
                )
                logger.info(f"Behavioral alert: pattern '{pattern['name']}' matched {len(matches)} events")

    except Exception as e:
        logger.error(f"Detection cycle error: {e}")
    finally:
        _running = False


def evaluate_pattern(pattern: Dict, events: List[Dict]) -> Optional[List[Dict]]:
    """Match pattern rules against a set of events."""
    rules = pattern.get("rules", {})
    if isinstance(rules, str):
        try:
            rules = json.loads(rules)
        except (json.JSONDecodeError, TypeError):
            rules = {}

    if not rules:
        return None

    threshold = rules.get("threshold", 5)
    window_seconds = rules.get("window_seconds", rules.get("window_minutes", 5) * 60)
    condition = rules.get("condition", {})
    event_type_filter = condition.get("event_type") or rules.get("event_type")
    source_filter = condition.get("source")

    cutoff = (datetime.utcnow() - timedelta(seconds=window_seconds)).isoformat()

    matching = []
    for event in events:
        if event.get("timestamp", "") < cutoff:
            continue
        # Skip events generated by the behavioral engine itself (prevent feedback loop)
        if event.get("source") == "julius-behavioral-engine":
            continue
        if event.get("event_type") == "behavioral_alert_generated":
            continue
        if event_type_filter and event.get("event_type") != event_type_filter:
            continue
        if source_filter and event.get("source") != source_filter:
            continue
        matching.append(event)

    if len(matching) >= threshold:
        return matching
    return None


def generate_alert(pattern: Dict, matches: List[Dict]) -> Dict:
    """Create an alert from a pattern match."""
    return {
        "alert_type": f"pattern_{pattern.get('pattern_type', 'behavioral')}",
        "severity": pattern.get("severity", "medium"),
        "message": f"Pattern '{pattern['name']}' triggered: {len(matches)} events matched in detection window",
        "data": {
            "pattern_id": pattern["id"],
            "pattern_name": pattern["name"],
            "matched_count": len(matches),
            "sample_events": [e.get("id") for e in matches[:5]],
            "detection_time": datetime.utcnow().isoformat(),
        },
    }


def is_engine_running() -> bool:
    return _running
